import { useState, useCallback } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { oneDark } from "react-syntax-highlighter/dist/esm/styles/prism";
import "./MarkdownRenderer.css";

const LOCAL_HOSTNAMES = new Set([
  "localhost",
  "127.0.0.1",
  "::1",
  "[::1]",
  "0.0.0.0",
]);

function isLocalUrl(href) {
  try {
    const url = new URL(href, window.location.origin);
    // Relative URLs resolve to current origin — always local
    if (!href.startsWith("http://") && !href.startsWith("https://")) {
      return true;
    }
    const hostname = url.hostname;
    if (LOCAL_HOSTNAMES.has(hostname)) return true;
    // Private-network ranges (LAN is still "local enough")
    if (
      hostname.endsWith(".local") ||
      hostname.endsWith(".localhost") ||
      hostname === window.location.hostname
    )
      return true;
    return false;
  } catch {
    // Malformed URL — don't open at all
    return false;
  }
}

function ExternalLink({ href, children }) {
  const [showWarning, setShowWarning] = useState(false);

  const handleClick = useCallback(
    (e) => {
      e.preventDefault();
      setShowWarning(true);
    },
    []
  );

  const handleContinue = useCallback(() => {
    window.open(href, "_blank", "noopener,noreferrer");
    setShowWarning(false);
  }, [href]);

  const handleCancel = useCallback(() => {
    setShowWarning(false);
  }, []);

  let displayHost;
  try {
    displayHost = new URL(href).hostname;
  } catch {
    displayHost = href;
  }

  return (
    <>
      <a
        href={href}
        onClick={handleClick}
        className="md-external-link"
        title={`External link: ${href}`}
      >
        {children}
        <span className="md-external-icon" aria-hidden="true"> ↗</span>
      </a>
      {showWarning && (
        <span
          className="md-external-overlay"
          onClick={handleCancel}
          role="dialog"
          aria-modal="true"
          aria-label="External link warning"
        >
          <span
            className="md-external-modal"
            onClick={(e) => e.stopPropagation()}
          >
            <span className="md-external-modal-icon">⚠️</span>
            <strong className="md-external-modal-title">
              External Link Warning
            </strong>
            <p className="md-external-modal-text">
              This link was generated by an AI model and will take you to an
              external site:
            </p>
            <code className="md-external-modal-url">{href}</code>
            <p className="md-external-modal-host">
              Destination: <strong>{displayHost}</strong>
            </p>
            <p className="md-external-modal-caution">
              Verify you trust this URL before continuing. AI models can produce
              links to phishing or malicious sites.
            </p>
            <span className="md-external-modal-actions">
              <button
                className="md-external-btn md-external-btn-cancel"
                onClick={handleCancel}
              >
                Cancel
              </button>
              <button
                className="md-external-btn md-external-btn-continue"
                onClick={handleContinue}
              >
                Open Link ↗
              </button>
            </span>
          </span>
        </span>
      )}
    </>
  );
}

function CodeBlock({ language, children }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(children);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  return (
    <div className="code-block-wrapper">
      <div className="code-block-header">
        <span className="code-block-language">{language || "text"}</span>
        <button
          className={`code-copy-btn ${copied ? "copied" : ""}`}
          onClick={handleCopy}
          title={copied ? "Copied!" : "Copy code"}
        >
          {copied ? "Copied!" : "Copy"}
        </button>
      </div>
      <SyntaxHighlighter
        style={oneDark}
        language={language || "text"}
        PreTag="div"
        customStyle={{
          margin: 0,
          borderRadius: "0 0 6px 6px",
          fontSize: "13px",
          background: "rgba(0, 0, 0, 0.4)",
        }}
        codeTagProps={{
          style: {
            fontFamily: "var(--font-mono)",
          },
        }}
      >
        {children}
      </SyntaxHighlighter>
    </div>
  );
}

function InlineCode({ children }) {
  return <code className="md-inline-code">{children}</code>;
}

export default function MarkdownRenderer({ content }) {
  return (
    <div className="markdown-content">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          code({ node, inline, className, children, ...props }) {
            const match = /language-(\w+)/.exec(className || "");
            const language = match ? match[1] : "";
            const codeString = String(children).replace(/\n$/, "");

            if (!inline && (match || codeString.includes("\n"))) {
              return <CodeBlock language={language}>{codeString}</CodeBlock>;
            }

            return <InlineCode {...props}>{children}</InlineCode>;
          },
          // Custom link handling — external links get an interstitial warning
          a({ href, children }) {
            if (href && !isLocalUrl(href)) {
              return <ExternalLink href={href}>{children}</ExternalLink>;
            }
            return (
              <a href={href} target="_blank" rel="noopener noreferrer">
                {children}
              </a>
            );
          },
          // Better table styling
          table({ children }) {
            return (
              <div className="md-table-wrapper">
                <table className="md-table">{children}</table>
              </div>
            );
          },
          // Better blockquote
          blockquote({ children }) {
            return <blockquote className="md-blockquote">{children}</blockquote>;
          },
          // Better lists
          ul({ children }) {
            return <ul className="md-list md-ul">{children}</ul>;
          },
          ol({ children }) {
            return <ol className="md-list md-ol">{children}</ol>;
          },
          // Better headings
          h1({ children }) {
            return <h1 className="md-heading md-h1">{children}</h1>;
          },
          h2({ children }) {
            return <h2 className="md-heading md-h2">{children}</h2>;
          },
          h3({ children }) {
            return <h3 className="md-heading md-h3">{children}</h3>;
          },
          h4({ children }) {
            return <h4 className="md-heading md-h4">{children}</h4>;
          },
          // Horizontal rule
          hr() {
            return <hr className="md-hr" />;
          },
          // Paragraphs
          p({ children }) {
            return <p className="md-paragraph">{children}</p>;
          },
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}
